version: '3.8'

services:
  lwt_bot:
    build: .
    container_name: lwt_bot
    volumes:
      - .:/home/appuser/app
    env_file:
      - .env
    depends_on:
      lwt_db:
        condition: service_healthy
      lwt_redis:
        condition: service_healthy
    entrypoint: /home/appuser/app/entrypoint.sh
    restart: unless-stopped

  lwt_db:
    image: postgres:16
    container_name: lwt_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  lwt_redis:
    image: redis:7-alpine
    container_name: lwt_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: