services:
  lwt_bot:
    platform: linux/arm64
    build: .
    container_name: lwt_bot
    volumes:
      - .:/home/appuser/app
    env_file:
      - stack.env
    depends_on:
      lwt_redis:
        condition: service_healthy
    entrypoint: alembic upgrade head && python ./lwt_app/main.py
    restart: unless-stopped

  lwt_redis:
    platform: linux/arm64
    image: redis:6-alpine
    container_name: lwt_redis
    restart: unless-stopped
    env_file:
      - stack.env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      lwt_db:
        condition: service_healthy

  lwt_db:
    platform: linux/arm64
    image: postgres:13-alpine
    container_name: lwt_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - stack.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: